export const images = {
  logo: "/logo.jpg",
  cmu: "/cmu.png",
  nitr: "/nitr.png",
  safeDrive: "/safeDrive.jpg",
  careBridge: "/carebridge.png",
  gpt2: "/gpt2.png",
  college: "/igdtuw.png",
  bg: "/bg.png",
  SpeedLine: "/SpeedLine.png",
  codeSage: "/codeSage.png",
  moi1: "/moi_1.jpeg",
  moi2: "/moi_2.jpeg",
  moi3: "/moi_3.jpeg",
  moi4: "/moi_4.jpeg",
  moi5: "/moi_5.jpeg",
  moi6: "/moi_6.jpeg",
  moi7: "/moi_7.jpeg",
  moi8: "/moi_8.jpeg",
  moi9: "/moi_9.jpeg",
  moi10: "/moi_10.jpeg",
  moi11: "/moi_11.jpeg",
};
